version: '3'
services:
  bdd:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD:password
      - MYSQL_DATABASE:wordpress
      - MYSQL_USER:wordpress
      - MYSQL_PASSWORD:wordpress
  
  wordpress:
    depends_on:
      - bdd
    image: wordpress:latest
    ports:
      - "8088:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST:bdd:3306
      - WORDPRESS_DB_USER:wordpress
      - WORDPRESS_DB_PASSWORD:wordpress
      - WORDPRESS_DB_NAME:wordpress

volumes:
  db_data: {}